## Deployment playbook goes here.
- name: Create directory
  file:
    path: /backend
    state: directory

- name: Extract backend artifcat
  unarchive:
    src: "files/artifact.tar.gz"
    dest: /backend
    remote_src: yes

- name: Starting backend
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start
