## Deployment playbook goes here.
- name: Create directory
  file:
    path: /backend
    state: directory

- name: Copy backend artifact
  amazon.aws.aws_s3:
    profile: public
    bucket: s3://udapeople-8b022f5
    mode: get
    object: "artifact.tar.gz"
    dest: "/backend/"

- name: "install node exporter."
  unarchive:
    src: /backend/artifact.tar.gz
    dest: /backend/
    remote_src: no

- name: Starting backend
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start
