## remove this first play
- name: "install dependencies."
  become: yes
  apt:
    name: ["tar", "gzip"]
    state: latest
    update_cache: yes

- name: Create directory
  file:
    path: ~/backend
    state: directory

- name: Copy artifact to /backend
  template:
    src: "files/artifact.tar.gz"
    dest: "~/backend/"

- name: "extract"
  unarchive:
    src: ~/backend/artifact.tar.gz
    dest: ~/backend/

- name: Starting backend
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start
