## Deployment playbook goes here.
- name: Create directory
  file:
    path: /backend
    state: directory

## move below out of playbook
- name: download install s3 module
  shell: |
    ansible-galaxy collection install amazon.aws

- name: "wait 5 seconds for install to complete."
  wait_for:
    timeout: 5

- name: Copy backend artifact
  amazon.aws.s3_bucket:
    profile: public
    bucket: s3://udapeople-8b022f5
    mode: get
    object: "artifact.tar.gz"
    dest: "/backend/"

- name: "install node exporter."
  unarchive:
    src: /backend/artifact.tar.gz
    dest: /backend/
    remote_src: no

- name: Starting backend
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start
